topos-protocol/topos-smart-contracts

- README.md
- package.json
- scripts/deploy-topos-msg-protocol-dynamic.ts
- tsconfig.json
Introduce new script to deploy Topos contracts without pre-deployed fixed const address deployer contract (to other non Polygon Edge networks, e.g. Hardhat node)
Usage:
```
npm run deploy:topos-msg-protocol-dynamic <node json-rpc endpoint> <sequencer private key>
```
This script is primarily intended for fast development and testing of interaction of external components with Topos smart contracts.
> feat: deploy contracts without const address deployer

- .github/workflows/npm-package.yml
This PR replaces the Github NPM registry with the official npmjs.com one, so that consumers don't have to add an `.npmrc` file detailing custom registries.
> ci: publish package to official npm registry

- .github/workflows/npm-package.yml
- package.json
#79 introduced the publication of the npm package to the npmjs.com registry. Unfortunately, the `--access public` flag for the `npm publish` command was missing, hence making the package private (with a failing publication).
This PR adds the missing flag and bumps the package version (we need to wait for `1.0.0` unpublication).
> fix: add missing npm pkg access

- contracts/examples/ERC20Messaging.sol
- contracts/interfaces/IERC20Messaging.sol
- contracts/interfaces/IToposMessaging.sol
- contracts/topos-core/ERC20Messaging.sol
- contracts/topos-core/ToposMessaging.sol
- package.json
- scripts/deploy-topos-msg-protocol-dynamic.ts
- scripts/deploy-topos-msg-protocol.ts
- scripts/test/send-token.ts
- test/topos-core/ToposMessaging.test.ts
This pull request introduces a division of the current `ToposMessaging.sol` smart contract into two separate contracts: a parent contract (`ToposMessaging.sol`) and a child contract (`ERC20Messaging.sol`). The rationale behind this design choice is based on the concept that the `ToposMessaging` contract is responsible for carrying out general input validation for the incoming transactions. After the common validation is completed, the data is redirected to the child contract, which handles any application-specific data validation.
In summary, each application-specific child smart contract intended for use in the cross-subnet messaging protocol inherits the parent contract, allowing dApp developers to focus solely on application-specific data validation.
Fixes TP-596
- Added …
> chore: split ToposMessaging & add ERC20Messaging

- .github/workflows/docker_build_push.yml
This PR replaces `pep440` with `semver` for the docker tag strategy.
- Use `semver` in docker workflow when selecting docker tags
> ci: use semver for docker tags

- .github/workflows/release-pipeline.yml
This PR adds a new CI workflow for sending Slack notifications upon new releases.
The Slack notification will help prevent multiple new releases from different stack components to miss each other's e2e tests run by the new `topos-network/e2e-tests` project.
> ci: add release-pipeline workflow

- .github/workflows/docker_build_push.yml
- .github/workflows/docker_utils.yml
This PR updates the docker CI workflow to have `e2e-tests`'s `frontend` workflow triggered right after the contracts docker workflow has run (and using the just new tag for e2e tests).
> test: trigger frontend e2e tests

- .github/workflows/docker_build_push.yml
#90 introduced triggering e2e tests remotely on many topos-smart-contracts triggers. This PR updates the condition of the e2e trigger job so that it is only run on PR updates (otherwise the relevant docker tag is not fetchable—because there are many of tem).
> fix: trigger e2e tests for PR updates only

- .github/workflows/docker_build_push.yml
#91 introduced filtering triggers for the e2e tests remote workflow execution, unfortunately double quotes were used instead of single quotes.
> fix: use single quotes in workflow if condition

- .github/workflows/sequencer-e2e.yml
This PR adds a CI workflow to trigger the sequencer-contracts e2e test remotely.
> test: trigger sequencer e2e tests

- contracts/interfaces/IToposCore.sol
- contracts/topos-core/ToposCore.sol
- test/topos-core/ToposCore.test.ts
This PR resolves the issue of retrieving the return value from a certificate that is stored within the `ToposCore` contract.
Fixes TP-607
- Changed the return value of the `getCertificate` method in `ToposCore` contract
> fix: return value of a storage cert

- contracts/interfaces/IERC20Messaging.sol
This PR refactors the parameters for the `sendToken` function of the `IERC20Messaging` interface to match the parameters of the implementation in the `ERC20Messaging` smart contract
Fixes TP-697
- Changed the order of the parameters of the `sendToken` function
> chore: rearrange args

- contracts/topos-core/SubnetRegistrator.sol
- scripts/deploy-subnet-registrator.ts
- scripts/deploy.ts
- scripts/register-subnet.ts
- test/topos-core/SubnetRegistrator.test.ts
This PR adds an admin parameter for the `SubnetRegistrator.sol` smart contract via an initialize function.
The rationale is to have a constant address for the `SubnetRegistrator.sol` smart contract while having access control.
Fixes TP-700
- Revert changes in the `deploy.ts` scripts introduced in #102
- Added a parameter `admin` in the `initialize` func of the `SubnerRegistrator.sol` smart contract
- Added `deploy-subnet-registrator.ts` script
- Made changes to the `register-subnet.ts` script to allow the sequencer/validator to register a subnet
> feat: add initialize func to SubnerRegistrator

- package.json
- scripts/register-subnet.ts
This PR adds an explicit gas limit in the register-subnet script to fix a gas estimation tx error.
> fix: set gas limit in register subnet script

- package.json
- scripts/deploy-subnet-registrator.ts
- scripts/register-subnet.ts
This PR fixes the issue introduced by #107 where a single private key is used both for creating the admin wallet capable of register a new subnet and the new subnet id. To fix this, we introduce a new arg to pass an `adminPrivateKey` separately from the `sequencerPrivateKey`.
[Passing e2e-tests workflow run](https://github.com/topos-protocol/e2e-tests/actions/runs/6165023442)
> fix: use right admin priv key for register subnet script

- scripts/deploy-topos-core.ts
This PR adds a standalone script to deploy and initialize the `ToposCore.sol` smart contract, with the proxy pattern, on any subnet (internal and external).
To run the script:
```
$ export PRIVATE_KEY=<private_key>
$ ts-node scripts/deploy-topos-core.ts <endpoint> <sequencer_priv_key> <gas_limit>
``` 
- Added the `deploy-topos-core.ts` script
> feat: add ToposCore deployment script

- contracts/examples/ERC20Messaging.sol
- scripts/test/send-token.ts
- test/topos-core/ToposMessaging.test.ts
- test/topos-core/shared/utils/common.ts
This PR removes the check for `External` ERC20 token addresses when deploying an ERC20 token via the Topos Cross-Subnet Messaging Protocol.
Only `Internal` tokens are allowed to be deployed.
Fixes TP-782
- Removed the address param from the input `params` for the `sendToken` method in `ERC20Messaging.sol` smart contract
- Adapted the unit tests to the changes
Changes the input `params` for the `deployToken` function so will require changes to the infra as well
> chore: remove check for existing tokens

- README.md
This PR adds Github/Shields badges to the repo `README`.
> chore(readme): add badges to README

- contracts/topos-core/AdminMultisigBase.sol
- contracts/topos-core/EternalStorage.sol
- contracts/topos-core/SubnetRegistrator.sol
- contracts/topos-core/ToposCore.sol
- contracts/topos-core/ToposCoreProxy.sol
- package-lock.json
- package.json
- scripts/const-addr-deployer.ts
- scripts/deploy-subnet-registrator.ts
- scripts/deploy-topos-core.ts
- scripts/deploy-topos-msg-protocol-dynamic.ts
- scripts/deploy-topos-msg-protocol.ts
- scripts/deploy.ts
- scripts/register-subnet.ts
- scripts/test/send-token.ts
- test/topos-core/BurnableMintableCappedERC20.test.ts
- test/topos-core/Bytes32Sets.test.ts
- test/topos-core/SubnetRegistrator.test.ts
- test/topos-core/ToposCore.test.ts
- test/topos-core/ToposMessaging.test.ts
- test/topos-core/shared/constants/certificates.ts
- test/topos-core/shared/utils/common.ts
- test/topos-core/shared/utils/mpt_proof.ts
- tsconfig.json
This PR updates `ethers` and `hardhat-toolbox` so that the global stack can upgrade `ethers` to `v6`.
Fixes TOO-397
> feat: update hardhat toolbox for ethers v6

- .solcover.js
This PR adds a Yul optimizer configuration for the Solidity compiler.
This resolves the failing `npm run coverage` command.
Fixes TP-830
- Added `.solcover.js` configuration file
> feat: add the compiler optimization profile

- package-lock.json
Bumps the `package-lock.json` ver to match the `package.lock` ver
`v3.0.0` -> `v3.1.0`
> chore: bump package-lock.json version to v3.1.0

- scripts/upgrade-topos-core.ts
This Pull Request introduces a TypeScript script that allows us to upgrade the logic contract of `ToposCore.sol`. This is necessary because when there is a newer version of `ToposCore.sol`, we need a method to switch to this updated version.
This upgrade process maintains the integrity of the `ToposCore`'s proxy contract, ensuring that all storage slots are preserved.
Fixes TP-850
- Adds the `upgrade-topos-core.ts` script
On a running network, have the following:
- `ToposCoreProxy` contract deployed
- `ToposCore` implementation contract deployed
- `ToposCoreProxy` `initialized` with the implementation contract's address
- `ConstAddressDeployer` contract deployed
- The `PRIVATE_KEY` env variable set (private key of the deployer account)
To run the script run the following command:
```
npx …
```
> feat: add `ToposCore` upgrade script

- contracts/interfaces/IToposCore.sol
- contracts/interfaces/IToposMessaging.sol
- contracts/topos-core/CodeHash.sol
- contracts/topos-core/ToposCore.sol
- contracts/topos-core/ToposMessaging.sol
- test/topos-core/ToposMessaging.test.ts
This PR resolves the issue with the `receiptHash` not being unique for two or more cross-subnet transactions.
Let's try to understand the issue with the following example. For two identical `sendToken` transactions from the same user on the same subnet, i.e. two transactions where the allowance amount and the arguments for the `sendToken` transaction are kept the same, we would end up in a situation where the `receiptHash` would also be identical for these two transactions. This is because there is no nonce for receipts as opposed to transactions where a combination of `from` and `nonce` is kept track of to prevent replay attacks. If the two transactions end up in different blocks (let's assume there are no other transactions in both blocks), then the `receiptsRoot` for both blocks would …
> feat: add unique receipts for cross-subnet transactions
